package br.ucsal.sqltool;

import java.sql.BatchUpdateException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JFrame;

public class Principal {

	public static void main(String[] args) {

		
		String url = "jdbc:hsqldb:file:./src/main/resources/banco";
		String user = "SA";
		String password = "";
		
		try {
			Connection connection = DriverManager.getConnection(url , user , password );
			JFrame tool = new Janela(connection);

			try { 
				ddl(connection);
			}catch (BatchUpdateException e) {
				System.out.println("O BANCO JÁ EXISTE ");
			}
			
		
			Statement statement = connection.createStatement();
			
			ResultSet resultSet = statement.executeQuery("SELECT * FROM ALUNO");
			
			while(resultSet.next()) {
				System.out.println("ID: "+resultSet.getInt(1));
				System.out.println("MATRICULA: "+resultSet.getString("MATRICULA"));
				System.out.println("NOME: "+resultSet.getString("NOME"));
			}
			
			resultSet.close();
			statement.close();
			//connection.close();
			
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
		
	}
	
	public static void ddl(Connection connection) throws SQLException {
		Statement statement = connection.createStatement();
		statement.addBatch("CREATE TABLE ALUNO (ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY, MATRICULA CHAR(10), "
				+ "NOME VARCHAR(150))");
		statement.addBatch("INSERT INTO ALUNO (MATRICULA,NOME) VALUES('20200201','PEDRO')");
		statement.addBatch("INSERT INTO ALUNO (MATRICULA,NOME) VALUES('20200202','MARIA')");
		statement.addBatch("INSERT INTO ALUNO (MATRICULA,NOME) VALUES('20200203','JOAO')");
		statement.addBatch("INSERT INTO ALUNO (MATRICULA,NOME) VALUES('20200204','VICTOR')");
		statement.addBatch("INSERT INTO ALUNO (MATRICULA,NOME) VALUES('20200205','JAMILE')");

		statement.executeBatch();
		statement.close();
		
	}

}
